class testData:
    def __init__(self):
        self.firstName= 'LiLi'
        self.lastName= 'Kingstone'
        self.age= 30
        self.email= 'test@test.com'
        self.salary= 12345
        self.department= 'QA'
        self.editedFirstName= 'Hashem'
        self.editedLastName= 'Hosseini'
